--Part – A 


--1. Create a cursor Course_Cursor to fetch all rows from COURSE table and display them. 
DECLARE COURSE_CURSOR CURSOR
FOR
	SELECT * FROM COURSE

OPEN COURSE_CURSOR
FETCH NEXT FROM COURSE_CURSOR
WHILE @@FETCH_STATUS=0
BEGIN
	PRINT 'COURSE ROW AFFECTED'
	FETCH NEXT FROM COURSE_CURSOR
END
CLOSE COURSE_CURSOR
DEALLOCATE COURSE_CURSOR;

--2. Create a cursor Student_Cursor_Fetch to fetch records in form of StudentID_StudentName (Example: 
--1_Raj Patel). 
DECLARE @STUDENTID INT;
DECLARE @STUNAME VARCHAR(50);

DECLARE STUDENT_CURSOR_FETCH CURSOR FOR
    SELECT STUDENTID, STUNAME
    FROM STUDENT

OPEN STUDENT_CURSOR_FETCH;

FETCH NEXT FROM STUDENT_CURSOR_FETCH INTO @STUDENTID, @STUNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT CAST(@STUDENTID AS VARCHAR) + '_' + @STUNAME;
    FETCH NEXT FROM STUDENT_CURSOR_FETCH INTO @STUDENTID, @STUNAME;
END;

CLOSE STUDENT_CURSOR_FETCH;
DEALLOCATE STUDENT_CURSOR_FETCH;

--3. Create a cursor to find and display all courses with Credits greater than 3. 
DECLARE @NAME VARCHAR(20), @CREDIT INT
DECLARE COURSE_CREDIT_CURSOR CURSOR
FOR
    SELECT COURSENAME, COURSECREDITS
    FROM COURSE
    WHERE COURSECREDITS>3;

OPEN COURSE_CREDIT_CURSOR

FETCH NEXT FROM COURSE_CREDIT_CURSOR
INTO @NAME, @CREDIT

WHILE @@FETCH_STATUS = 0
BEGIN
   PRINT @NAME + ' HAS ' + CAST(@CREDIT AS VARCHAR) + ' CREDITS';
   FETCH NEXT FROM COURSE_CREDIT_CURSOR INTO @NAME, @CREDIT;
END;

CLOSE COURSE_CREDIT_CURSOR;
DEALLOCATE COURSE_CREDIT_CURSOR;


--4. Create a cursor to display all students who enrolled in year 2021 or later. 
DECLARE @STUDENTNAME VARCHAR(20), @ENROLLYEAR INT
DECLARE STUDENT_ENROLL_CURSOR CURSOR 
FOR
    SELECT STUNAME, STUENROLLMENTYEAR 
    FROM STUDENT WHERE STUENROLLMENTYEAR >= 2021;

OPEN STUDENT_ENROLL_CURSOR;
FETCH NEXT FROM STUDENT_ENROLL_CURSOR INTO @STUDENTNAME, @ENROLLYEAR;

WHILE @@FETCH_STATUS = 0
BEGIN
   PRINT @STUDENTNAME + ' ENROLLED IN ' + CAST(@ENROLLYEAR AS VARCHAR);
   FETCH NEXT FROM STUDENT_ENROLL_CURSOR INTO @STUDENTNAME, @ENROLLYEAR;
END;

CLOSE STUDENT_ENROLL_CURSOR;
DEALLOCATE STUDENT_ENROLL_CURSOR;

--5. Create a cursor Course_CursorUpdate that retrieves all courses and increases Credits by 1 for courses 
--with Credits less than 4.
DECLARE @CID VARCHAR(10), @CNAME VARCHAR(20)
DECLARE COURSE_CURSORUPDATE CURSOR
FOR 
    SELECT COURSENAME, COURSECREDITS 
    FROM COURSE 
    WHERE COURSECREDITS<4
OPEN COURSE_CURSORUPDATE
FETCH NEXT FROM COURSE_CURSORUPDATE INTO @CID, @CNAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE COURSE
    SET CourseCredits = CourseCredits+1
    WHERE CourseCredits<4
END;
CLOSE COURSE_CURSORUPDATE;
DEALLOCATE COURSE_CURSORUPDATE;

SELECT * FROM COURSE

--6. Create a Cursor to fetch Student Name with Course Name (Example: Raj Patel is enrolled in Database 
--Management System)
DECLARE @STUDENTNAME VARCHAR(50);
DECLARE @COURSENAME VARCHAR(50);

DECLARE STUDENT_COURSE_CURSOR CURSOR 
FOR
    SELECT S.STUNAME, C.COURSENAME
    FROM STUDENT S
    JOIN ENROLLMENT  E ON S.STUDENTID = E.STUDENTID
    JOIN COURSE C ON C.COURSEID = E.COURSEID;

OPEN STUDENT_COURSE_CURSOR;

FETCH NEXT FROM STUDENT_COURSE_CURSOR INTO @STUDENTNAME, @COURSENAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @STUDENTNAME + ' is enrolled in ' + @COURSENAME;
    FETCH NEXT FROM STUDENT_COURSE_CURSOR INTO @STUDENTNAME, @COURSENAME;
END;

CLOSE STUDENT_COURSE_CURSOR;
DEALLOCATE STUDENT_COURSE_CURSOR;




--7. Create a cursor to insert data into new table if student belong to ‘CSE’ department. (create new table 
--CSEStudent with relevant columns)
CREATE TABLE STUDENT_CSE(
    STUID INT,
    SNAME VARCHAR(20),
    SDEPT VARCHAR(10)
);
DECLARE @ID INT, @SNAME VARCHAR(20), @DEPT VARCHAR(20)
DECLARE CURSOR_STUDENT_CSE CURSOR
FOR
    SELECT STUDENTID, STUNAME, STUDEPARTMENT
    FROM STUDENT
    WHERE StuDepartment='CSE'

OPEN CURSOR_STUDENT_CSE;
FETCH NEXT FROM CURSOR_STUDENT_CSE INTO @ID,@SNAME,@DEPT

WHILE @@FETCH_STATUS=0
BEGIN
    INSERT INTO STUDENT_CSE(STUID, SNAME ,SDEPT) VALUES (@ID,@SNAME,@DEPT)

    FETCH NEXT FROM CURSOR_STUDENT_CSE INTO @ID,@SNAME,@DEPT
END
CLOSE CURSOR_STUDENT_CSE
DEALLOCATE CURSOR_STUDENT_CSE

SELECT * FROM STUDENT_CSE;

--Part – B 

INSERT INTO ENROLLMENT VALUES (STUDENTID,COURSEID,ENROLLMENTDATE,GRADE,ENROLLMENTSTATUS)
VALUES (2,CS101,2021-07-01,NULL,COMPLETED)



--8. Create a cursor to update all NULL grades to 'F' for enrollments with Status 'Completed'
DECLARE @ENROLLID INT;

DECLARE GRADE_UPDATE_CURSOR CURSOR 
FOR
    SELECT ENROLLMENTID FROM ENROLLMENT
    WHERE ENROLLMENTSTATUS = 'COMPLETED' AND GRADE IS NULL;

OPEN GRADE_UPDATE_CURSOR;

FETCH NEXT FROM GRADE_UPDATE_CURSOR INTO @ENROLLID;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE ENROLLMENT
    SET GRADE = 'F'
    WHERE ENROLLMENTID = @ENROLLID;

    PRINT 'UPDATED ENROLLID ' + CAST(@ENROLLID AS VARCHAR) + ' TO GRADE F';

    FETCH NEXT FROM GRADE_UPDATE_CURSOR INTO @ENROLLID;
END;

CLOSE GRADE_UPDATE_CURSOR;
DEALLOCATE GRADE_UPDATE_CURSOR;

SELECT * FROM ENROLLMENT;

--9. Cursor to show Faculty with Course they teach (EX: Dr. Sheth teaches Data structure) 
DECLARE @FACULTYNAME VARCHAR(50);
DECLARE @COURSENAME VARCHAR(50);

DECLARE FACULTY_COURSE_CURSOR CURSOR 
FOR
    SELECT F.FACULTYNAME, C.COURSENAME
    FROM FACULTY F
    JOIN COURSE_ASSIGNMENT CA ON F.FACULTYID = CA.FACULTYID
    JOIN COURSE C ON CA.COURSEID = C.COURSEID;

OPEN FACULTY_COURSE_CURSOR;

FETCH NEXT FROM FACULTY_COURSE_CURSOR INTO @FACULTYNAME, @COURSENAME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @FACULTYNAME + ' teaches ' + @COURSENAME;
    FETCH NEXT FROM FACULTY_COURSE_CURSOR INTO @FACULTYNAME, @COURSENAME;
END;

CLOSE FACULTY_COURSE_CURSOR;
DEALLOCATE FACULTY_COURSE_CURSOR;


--Part – C 

--10. Cursor to calculate total credits per student (Example: Raj Patel has total credits = 15)
DECLARE @STUDENTNAME VARCHAR(50);
DECLARE @TOTALCREDITS INT;

DECLARE STUDENT_CREDIT_CURSOR CURSOR 
FOR
    SELECT S.STUNAME, SUM(C.COURSECREDITS) AS TOTALCREDITS
    FROM STUDENT S
    JOIN ENROLLMENT E ON S.STUDENTID = E.STUDENTID
    JOIN COURSE C ON E.COURSEID = C.COURSEID
    GROUP BY S.STUNAME;

OPEN STUDENT_CREDIT_CURSOR;

FETCH NEXT FROM STUDENT_CREDIT_CURSOR INTO @STUDENTNAME, @TOTALCREDITS;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @STUDENTNAME + ' has total credits = ' + CAST(@TOTALCREDITS AS VARCHAR);
    FETCH NEXT FROM STUDENT_CREDIT_CURSOR INTO @STUDENTNAME, @TOTALCREDITS;
END;

CLOSE STUDENT_CREDIT_CURSOR;
DEALLOCATE STUDENT_CREDIT_CURSOR;