USE CSE_4B_368

--Part-A

--1. Write a scalar function to print "Welcome to DBMS Lab".
CREATE OR ALTER FUNCTION FN_WELCOMEMSG()
RETURNS VARCHAR(20)
AS 
BEGIN
	RETURN 'WELCOME TO DBMS LAB'
END

SELECT DBO.FN_WELCOMEMSG();

--2. Write a scalar function to calculate simple interest.
CREATE OR ALTER FUNCTION FN_SIMPLEINTEREST(
	@PRICE FLOAT,
	@RATE FLOAT,
	@TIME FLOAT
)
RETURNS FLOAT
AS
BEGIN
	RETURN (@PRICE*@RATE*@TIME)/100;
END

SELECT DBO.FN_SIMPLEINTEREST(1000,5,2);

--3. Function to Get Difference in Days Between Two Given Dates
CREATE OR ALTER FUNCTION FN_DATEDIFF(@DATE1 DATE, @DATE2 DATE)
RETURNS INT
AS
BEGIN
	RETURN DATEDIFF(DAY,@DATE1,@DATE2)
END

SELECT DBO.FN_DATEDIFF('2007-01-01','2007-01-17')

--4. Write a scalar function which returns the sum of Credits for two given CourseIDs.
CREATE OR ALTER FUNCTION FN_SUMOF_CREADTIS(@ID1 VARCHAR(10), @ID2 VARCHAR(10))
RETURNS INT
AS
BEGIN
	DECLARE @SUM INT
	SET @SUM = (SELECT COURSECREDITS FROM COURSE WHERE COURSEID=@ID1) + (SELECT COURSECREDITS FROM COURSE WHERE COURSEID=@ID2)
	RETURN @SUM
END

SELECT DBO.FN_SUMOF_CREADTIS('CS101','CS201');

--5. Write a function to check whether the given number is ODD or EVEN.
CREATE OR ALTER FUNCTION FN_CHECKODDEVEN(@NUM INT)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @RESULT VARCHAR(20)
	IF(@NUM%2=0)
		SET @RESULT='EVEN'
	ELSE 
		SET @RESULT='ODD'

	RETURN @RESULT
END

SELECT DBO.FN_CHECKODDEVEN(7);

--6. Write a function to print number from 1 to N. (Using while loop)
CREATE OR ALTER FUNCTION FN_PRINT_1TON(@NUMBER INT)
RETURNS VARCHAR(200)
AS
BEGIN
	DECLARE @RESULT VARCHAR(200),@COUNT INT
	SET @RESULT = ''
	SET @COUNT=1
	WHILE(@COUNT<=@NUMBER)
	BEGIN
		SET @RESULT = @RESULT+ ' '+CAST(@COUNT AS VARCHAR)
		SET @COUNT = @COUNT+1 
	END
	RETURN @RESULT
END

SELECT DBO.FN_PRINT_1TON(5)

--7. Write a scalar function to calculate factorial of total credits for a given CourseID.
CREATE OR ALTER FUNCTION FN_FAC_CREDITS(@ID VARCHAR(10))
RETURNS INT
AS
BEGIN
	DECLARE @CREDITS INT;
	DECLARE @FACTORIAL INT = 1;
	DECLARE @I INT = 1;

	SET @CREDITS = (SELECT COURSECREDITS FROM COURSE WHERE COURSEID = @ID)

	WHILE (@I<=@CREDITS)
	BEGIN
		SET @FACTORIAL = @FACTORIAL*@I
		SET @I = @I+1
	END
	RETURN @FACTORIAL 
END

SELECT DBO.FN_FAC_CREDITS('IT201');

--8. Write a scalar function to check whether a given EnrollmentYear is in the past, current or future (Case
--statement)
CREATE OR ALTER FUNCTION FN_ENROLLMENTYEAR(@YEAR INT)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @RESULT VARCHAR(20)
	RETURN CASE 
		WHEN @YEAR<YEAR(GETDATE()) THEN 'PAST YEAR'
		WHEN @YEAR>YEAR(GETDATE()) THEN 'FUTURE'
		ELSE 'CURRENT YEAR'
	END
END

SELECT DBO.FN_ENROLLMENTYEAR(2003);

--9. Write a table-valued function that returns details of students whose names start with a given letter.
CREATE OR ALTER FUNCTION FN_STUBYLETTER(@LETTER VARCHAR(5))
RETURNS TABLE
AS
	RETURN (SELECT * FROM STUDENT WHERE STUNAME LIKE @LETTER+'%');

SELECT * FROM DBO.FN_STUBYLETTER('A')

--10. Write a table-valued function that returns unique department names from the STUDENT table.
CREATE OR ALTER FUNCTION FN_UNIQUE_DEPARTMENT()
RETURNS TABLE
AS
	RETURN (SELECT DISTINCT STUDEPARTMENT FROM STUDENT);

SELECT * FROM DBO.FN_UNIQUE_DEPARTMENT();


--Part-B

--11. Write a scalar function that calculates age in years given a DateOfBirth.
CREATE OR ALTER
--12. Write a scalar function to check whether given number is palindrome or not.
--13. Write a scalar function to calculate the sum of Credits for all courses in the 'CSE' department.
CREATE OR ALTER FUNCTION FN_SUMCREDITS ()
RETURNS INT
AS
BEGIN
    DECLARE @TOTALCREDITS INT;
    SELECT @TOTALCREDITS = SUM(COURSECREDITS)
    FROM COURSE
    WHERE COURSEDEPARTMENT = 'CSE';

    RETURN @TOTALCREDITS
END;

SELECT DBO.FN_SUMCREDITS();

--14. Write a table-valued function that returns all courses taught by faculty with a specific designation.
CREATE OR ALTER FUNCTION FN_DESIGNATION(@DESIGNATION VARCHAR(30)
RETURNS TABLE 
AS
	RETURN (SELECT COURSE.COURSEID, COURSE.COURSENAME, COURSE.COURSEDEPARTMENT, FACULTY.FacultyName
			FROM COURSE
			JOIN FACULTY
			ON FACULTY.)