--Table : Log(LogMessage varchar(100), logDate Datetime) 
CREATE TABLE LOG(
    LOGMESSAGE VARCHAR(100),
    LOGDATE DATETIME
);

--Part – A 


--1. Create trigger for printing appropriate message after student registration.
CREATE OR ALTER TRIGGER TR_AFTER_STUDENT_REG
ON STUDENT
AFTER INSERT
AS
BEGIN
    PRINT 'STUDENT IS REGISTERED';
END;

INSERT INTO STUDENT VALUES (11,'RAJ SHAH','RAJ@SHAH.EDU','996352410','CSE','2003-12-25',1999,NULL);

SELECT * FROM STUDENT 

DROP TRIGGER TR_AFTER_STUDENT_REG;

--2. Create trigger for printing appropriate message after faculty deletion. 
CREATE OR ALTER TRIGGER TR_AFTER_FACULTY_DELETE
ON FACULTY
AFTER DELETE
AS
BEGIN
    PRINT 'FACULTY IS DELETED';
END;

INSERT INTO FACULTY VALUES (108,'IYER SHAH','IYER@SHAH.EDU','ICT','PROFESSOR','1999-07-20');

DELETE FROM FACULTY
WHERE FacultyID = 108;

SELECT * FROM FACULTY;

DROP TRIGGER TR_AFTER_FACULTY_DELETE;

--3. Create trigger for monitoring all events on course table. (print only appropriate message) 
CREATE OR ALTER TRIGGER TRG_AFTER_COURSE_EVENTS
ON COURSE
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    PRINT 'COURSE TABLE EVENT OCCURRED';
END;

SELECT * FROM COURSE;

INSERT INTO COURSE VALUES ('C100','DATA SYSTEMS',5,'ICT',2);

UPDATE COURSE
SET CourseID = 'C101'
WHERE COURSEID = 'C100';

DELETE FROM COURSE
WHERE CourseID = 'C101';

DROP TRIGGER TRG_AFTER_COURSE_EVENTS;

--4. Create trigger for logging data on new student registration in Log table.
CREATE OR ALTER TRIGGER TR_AFTER_LOGTABLE
ON STUDENT
AFTER INSERT
AS
BEGIN
    INSERT INTO LOG VALUES('STUDENT IS REGISTERED',GETDATE())
END;

INSERT INTO STUDENT VALUES (12,'PRIYA SHAH','PRIYA@SHAH.EDU','996352410','CSE','2003-11-25',1997,NULL);

SELECT * FROM LOG;


DROP TRIGGER TR_AFTER_LOGTABLE;

--5. Create trigger for auto-uppercasing faculty names. 
CREATE OR ALTER TRIGGER TR_UPPERCASE_FACULTY
ON FACULTY
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE FACULTY
    SET FACULTYNAME = UPPER(FACULTYNAME)
    WHERE FACULTYID IN (SELECT FACULTYID FROM INSERTED);
END;

SELECT * FROM FACULTY;

INSERT INTO FACULTY VALUES (108,'iyer joshi','IYER@SHAH.EDU','ICT','PROFESSOR','1999-07-20');

DROP TRIGGER TR_UPPERCASE_FACULTY

--6. Create trigger for calculating faculty experience (Note: Add required column in faculty table) 

ALTER TABLE FACULTY
ADD EXPERIENCE INT;

CREATE OR ALTER TRIGGER TRG_CALC_FACULTY_EXPERIENCE
ON FACULTY
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE FACULTY
    SET EXPERIENCE = DATEDIFF(YEAR, FACULTYJOININGDATE, GETDATE())
    WHERE FACULTYID IN (SELECT FACULTYID FROM INSERTED);
END;

INSERT INTO FACULTY VALUES (108,'iyer joshi','IYER@SHAH.EDU','ICT','PROFESSOR','1999-07-20',NULL);

DROP TRIGGER TRG_CALC_FACULTY_EXPERIENCE;

--Part – B 
--7. Create trigger for auto-stamping enrollment dates. 


--8. Create trigger for logging data After course assignment - log course and faculty detail.




--Part - C 
--9. Create trigger for updating student phone and print the old and new phone number. 
CREATE OR ALTER TRIGGER TRG_UPDATE_STUDENT_PHONE
ON STUDENT
AFTER UPDATE
AS
BEGIN
        SELECT 'OLD PHONE: ' + CAST(DELETED.STUPHONE AS VARCHAR) +
               ' NEW PHONE: ' + CAST(INSERTED.STUPHONE AS VARCHAR)
        FROM DELETED, INSERTED
        WHERE DELETED.STUDENTID = INSERTED.STUDENTID;
END;

UPDATE STUDENT 
SET STUPHONE = '9898'
WHERE STUDENTID = 2;

SELECT * FROM STUDENT;

DROP TRIGGER TRG_UPDATE_STUDENT_PHONE;

--10. Create trigger for updating course credit log old and new credits in log table.
CREATE OR ALTER TRIGGER TRG_UPDATE_COURSE_CREDIT
ON COURSE
AFTER UPDATE
AS
    BEGIN
        INSERT INTO LOG(LOGMESSAGE, LOGDATE)
        SELECT 'COURSE ' + CAST(I.COURSEID AS VARCHAR) +
               ' CREDIT CHANGED FROM ' + CAST(D.COURSECREDITS AS VARCHAR) +
               ' TO ' + CAST(I.COURSECREDITS AS VARCHAR),
               GETDATE()
        FROM DELETED D, INSERTED I
        WHERE D.COURSEID = I.COURSEID;
    END


UPDATE COURSE 
SET CourseCredits = 9
WHERE COURSENAME = 'Data Structures'

SELECT * FROM LOG;

SELECT * FROM COURSE;

DROP TRIGGER TRG_UPDATE_COURSE_CREDIT;